### ISSUE TITLE
Database Setup / First Migration

### ISSUE THREAD

**Issue by zstix** [zstix/summit-tracker#1]
## Tasks
- [x] Initial migration file
- [ ] Get tables set up
- [ ] Install bookshelf
- [ ] Clean up configuration (multiple environments)
- [ ] Documentation
