### ISSUE TITLE
Dummy Data

### ISSUE THREAD

**Issue by zstix** [zstix/summit-tracker#2]
## Tasks
- [ ] Create test seed file
- [ ] CI process for spinning up test database
- [ ] CI process for tearing down test database
- [ ] Locations
- [ ] Areas
- [ ] Climbs
- [ ] Users
- [ ] Summits
- [ ] Levels (actual data)
- [ ] Documentation
