### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by zstix** [zstix/summit-tracker#3]
## Tasks
- [ ] Users
  - [ ] GET `/users`
    - [ ] Filter
    - [ ] Sort
    - [ ] Paginate
  - [ ] GET `/users/{id}`
  - [ ] PUT `/users/{id}`
  - [ ] POST `/users`
  - [ ] DELETE `/users`
- [ ] Locations
  - [ ] GET `/locations`
    - [ ] Sort
    - [ ] Paginate
  - [ ] GET `/locations/{id}`
  - [ ] PUT `/locations/{id}`
  - [ ] POST `/locations`
  - [ ] DELETE `/locations`
- [ ] Areas
    - [ ] Filter
    - [ ] Sort
    - [ ] Paginate
  - [ ] GET `/areas`
  - [ ] GET `/areas/{id}`
  - [ ] PUT `/areas/{id}`
  - [ ] POST `/areas`
  - [ ] DELETE `/areas`
- [ ] Climbs
    - [ ] Filter
    - [ ] Sort
    - [ ] Paginate
  - [ ] GET `/climbs`
  - [ ] GET `/climbs/{id}`
  - [ ] PUT `/climbs/{id}`
  - [ ] POST `/climbs`
  - [ ] DELETE `/climbs`
- [ ] Summits
    - [ ] Filter
    - [ ] Sort
    - [ ] Paginate
  - [ ] GET `/summits`
  - [ ] GET `/summits/{id}`
  - [ ] PUT `/summits/{id}`
  - [ ] POST `/summits`
  - [ ] DELETE `/summits`
