### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by zstix** [zstix/summit-tracker#5]
## Tasks
- [ ] Lock down API routes
  - _Specific routes to be determined_
- [ ] Create login flow
- [ ] Create password reset flow
- [ ] Tests
- [ ] Documentation
